INSERT INTO concerts (id, concert_name, artist_name, description, capacity)
VALUES (uuid_generate_v4(), 'Electric Nights Festival', 'The Synth Lords',
        'An electrifying night of synthwave music under the stars.', 50),
       (uuid_generate_v4(), 'Rock the World', 'Stonehaven',
        'Join us for a thrilling rock concert that will shake the earth.', 50),
       (uuid_generate_v4(), 'Jazz and Blues Evening', 'Smooth Groove Collective',
        'A mellow evening filled with the smooth sounds of jazz and blues.', 15),
       (uuid_generate_v4(), 'Hip Hop Hustle', 'Beatz & Rhyme',
        'Experience the raw energy of hip hop with this explosive performance.', 30),
       (uuid_generate_v4(), 'Country Roads Live', 'The Dusty Boots',
        'Feel the heart of country music with this live outdoor concert.', 20),
       (uuid_generate_v4(), 'Symphony in the Park', 'Orchestra Magnifique',
        'A beautiful evening of classical music in the park.', 50),
       (uuid_generate_v4(), 'Pop Explosion', 'Neon Dreams',
        'A vibrant pop concert that will leave you dancing all night long.', 10),
       (uuid_generate_v4(), 'Indie Vibes', 'The Wanderers',
        'An intimate indie concert showcasing the best of the underground scene.', 15),
       (uuid_generate_v4(), 'Metal Mayhem', 'Iron Roar', 'A headbanging metal concert that will push your limits.',
        25),
       (uuid_generate_v4(), 'R&B Groove', 'Soul Serenade', 'Get lost in the soulful rhythms of R&B music.', 30),
       (uuid_generate_v4(), 'Reggae Sunfest', 'Island Vibes',
        'A sunny day filled with the smooth beats of reggae music.', 80),
       (uuid_generate_v4(), 'Electronic Euphoria', 'DJ Pulsewave',
        'An electronic music concert that will take you on a journey through sound.', 15),
       (uuid_generate_v4(), 'Acoustic Night', 'Strings & Harmony', 'A cozy acoustic concert with beautiful melodies.',
        10),
       (uuid_generate_v4(), 'Alternative Escape', 'Echoes of Tomorrow',
        'Experience the raw and authentic sounds of alternative rock.', 20),
       (uuid_generate_v4(), 'Latin Fiesta', 'Salsa Beats',
        'A lively Latin music concert that will make you move your feet.', 30),
       (uuid_generate_v4(), 'Folk Fest', 'The Mountain Singers',
        'A heartwarming folk music festival in a rustic setting.', 25),
       (uuid_generate_v4(), 'Punk Rock Revolution', 'Anarchy Avenue',
        'A high-energy punk rock concert that defies the norms.', 40),
       (uuid_generate_v4(), 'EDM Extravaganza', 'Bass Drop', 'An epic EDM concert with mind-blowing drops and beats.',
        10),
       (uuid_generate_v4(), 'Classical Masterpieces', 'The Grand Philharmonic',
        'A night of timeless classical music performed by a world-class orchestra.', 15),
       (uuid_generate_v4(), 'Soulful Sunday', 'The Velvet Tones',
        'End your weekend with the soothing sounds of soul music.', 20);
