services:
  postgresql:
    image: postgres:16.1
    container_name: postgres-tickets
    ports:
      - 5431:5432
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=ticketsdb'
      - 'POSTGRES_PASSWORD=postgres'