services:
  postgresql:
    image: postgres:16.1
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=concertdb'
      - 'POSTGRES_PASSWORD=postgres'